criaCartao(
    'Programação',
    'O que é Python?',
    'O Python é uma linguagm de programação'
)

criaCartao(
    'Geeografia',
    'Qua a capita daFrança?',
    'A capital da França é Paria'
)

criaCartao(
    'Programação',
    'O que é uma função',
    'Uma função é  um bloco de código que executa alguma tarefa'
)

criaCartao(
    'Lingua inglesa',
    'Como se diz oi em inglês',
    'Oi em inglês é HI(RAI)'
)